### ISSUE TITLE
Is it compatible with Laravel 7

### ISSUE THREAD

**Issue by we-subrat-b** [ctwillie/laravel-usps#5]
Is it compatible with Laravel 7?

**Comment by ctwillie** [comment]
@sbhol2008 So sorry I'm just now seeing this. I'm using Gitlab nowadays. I could easily make it Laravel 7 or 8 compatible for you if you still are interested. I'm not really keeping this repo maintained honestly. 

Im sure you have found a solution by now, but [this repo](https://github.com/johnpaulmedina/laravel-usps) is a great alternative.
